### ISSUE TITLE
符号変換の件

### ISSUE THREAD

**Issue by c0a21025ab** [c0a21085/ProjExD#5]
https://github.com/c0a21085/ProjExD/blob/69dbf48e2c39df7c55f0bd3c3880bfcc0ab894d5/ex02/calc.py#L44

入力されている数字に-1を掛けたらいいと思います

**Comment by c0a21085** [comment]
参考にします！
ただ、数値以外が入力された場合の対処を考えていなかったので、
エラーの対応込みでまとまり次第改善します！！
