### ISSUE TITLE
ランダム生成の迷路なので、ゴールの位置を固定してしまうと、迷路生成時に壁に埋まってしまう可能性があるのでは？

### ISSUE THREAD

**Issue by c0a21123** [c0a21085/ProjExD#9]
https://github.com/c0a21085/ProjExD/blob/f8dd94962182dc4f2239a0654b7b9324f34a563c/ex03/maze.py#L45

**Comment by c0a21085** [comment]
何度も実行させた結果､スタート地点とゴール地点には確実に道が出来ていました。
ただ、もっと回数をこなせば本当に100％そうなるか確証はないので、コードを再確認したうえで改善を検討します。
